; Listing generated by Microsoft (R) Optimizing Compiler Version 19.44.35228.0 

include listing.inc

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	_Avx2WmemEnabledWeakValue
;	COMDAT _Avx2WmemEnabledWeakValue
_BSS	SEGMENT
_Avx2WmemEnabledWeakValue DD 01H DUP (?)
_BSS	ENDS
PUBLIC	__local_stdio_printf_options
PUBLIC	_vfprintf_l
PUBLIC	printf
PUBLIC	?signbit@@YA_NM@Z				; signbit
PUBLIC	?quiet_NaN@?$numeric_limits@M@std@@SAMXZ	; std::numeric_limits<float>::quiet_NaN
PUBLIC	?sel_only@@YAXPEBM0PEAM@Z			; sel_only
PUBLIC	?sel_then_sqrt@@YAXPEBM0PEAM@Z			; sel_then_sqrt
PUBLIC	?sel_then_neg@@YAXPEBM0PEAM@Z			; sel_then_neg
PUBLIC	?sel_lt_then_sqrt@@YAXPEBM0PEAM@Z		; sel_lt_then_sqrt
PUBLIC	main
PUBLIC	?_OptionsStorage@?1??__local_stdio_printf_options@@9@4_KA ; `__local_stdio_printf_options'::`2'::_OptionsStorage
PUBLIC	??_C@_05HLLAPNIN@?$CF?946s@			; `string'
PUBLIC	??_C@_00CNPNBAHC@@				; `string'
PUBLIC	??_C@_05CNAAINAH@?5?$CFs?$CFg@			; `string'
PUBLIC	??_C@_01EEMJAFIK@?6@				; `string'
PUBLIC	??_C@_0CF@DNJEPAFA@x?5?$DN?5?$CL0?5?90?5nan?54?5?5?5?5?5y?5?$DN?5?90?5?$CL0?59@ ; `string'
PUBLIC	??_C@_0L@DJHLACHI@?$CIx?$DM?$DNy?$CJ?$DPy?3x@	; `string'
PUBLIC	??_C@_0BB@FKNPFCLB@sqrt?$CI?$CIx?$DM?$DNy?$CJ?$DPy?3x?$CJ@ ; `string'
PUBLIC	??_C@_0O@CDCMDCFE@?9?$CI?$CIx?$DM?$DNy?$CJ?$DPy?3x?$CJ@ ; `string'
PUBLIC	??_C@_0BA@ENBOJJDF@sqrt?$CI?$CIx?$DMy?$CJ?$DPy?3x?$CJ@ ; `string'
PUBLIC	__real@7fc00000
PUBLIC	__xmm@408000007fc000008000000000000000
PUBLIC	__xmm@7fc00000411000000000000080000000
PUBLIC	__xmm@80000000800000008000000080000000
EXTRN	__acrt_iob_func:PROC
EXTRN	__stdio_common_vfprintf:PROC
EXTRN	_fdsign:PROC
EXTRN	_fltused:DWORD
;	COMDAT ?_OptionsStorage@?1??__local_stdio_printf_options@@9@4_KA
_BSS	SEGMENT
?_OptionsStorage@?1??__local_stdio_printf_options@@9@4_KA DQ 01H DUP (?) ; `__local_stdio_printf_options'::`2'::_OptionsStorage
_BSS	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$_vfprintf_l DD imagerel $LN4
	DD	imagerel $LN4+80
	DD	imagerel $unwind$_vfprintf_l
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$printf DD imagerel $LN6
	DD	imagerel $LN6+83
	DD	imagerel $unwind$printf
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?signbit@@YA_NM@Z DD imagerel $LN4
	DD	imagerel $LN4+19
	DD	imagerel $unwind$?signbit@@YA_NM@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?show@@YAXPEBDPEBM@Z DD imagerel ?show@@YAXPEBDPEBM@Z
	DD	imagerel ?show@@YAXPEBDPEBM@Z+211
	DD	imagerel $unwind$?show@@YAXPEBDPEBM@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$main DD	imagerel $LN8
	DD	imagerel $LN8+199
	DD	imagerel $unwind$main
pdata	ENDS
;	COMDAT __xmm@80000000800000008000000080000000
CONST	SEGMENT
__xmm@80000000800000008000000080000000 DB 00H, 00H, 00H, 080H, 00H, 00H, 00H
	DB	080H, 00H, 00H, 00H, 080H, 00H, 00H, 00H, 080H
CONST	ENDS
;	COMDAT __xmm@7fc00000411000000000000080000000
CONST	SEGMENT
__xmm@7fc00000411000000000000080000000 DB 00H, 00H, 00H, 080H, 00H, 00H, 00H
	DB	00H, 00H, 00H, 010H, 'A', 00H, 00H, 0c0H, 07fH
CONST	ENDS
;	COMDAT __xmm@408000007fc000008000000000000000
CONST	SEGMENT
__xmm@408000007fc000008000000000000000 DB 00H, 00H, 00H, 00H, 00H, 00H, 00H
	DB	080H, 00H, 00H, 0c0H, 07fH, 00H, 00H, 080H, '@'
CONST	ENDS
;	COMDAT __real@7fc00000
CONST	SEGMENT
__real@7fc00000 DD 07fc00000r			; nan
CONST	ENDS
;	COMDAT ??_C@_0BA@ENBOJJDF@sqrt?$CI?$CIx?$DMy?$CJ?$DPy?3x?$CJ@
CONST	SEGMENT
??_C@_0BA@ENBOJJDF@sqrt?$CI?$CIx?$DMy?$CJ?$DPy?3x?$CJ@ DB 'sqrt((x<y)?y:x'
	DB	')', 00H					; `string'
CONST	ENDS
;	COMDAT ??_C@_0O@CDCMDCFE@?9?$CI?$CIx?$DM?$DNy?$CJ?$DPy?3x?$CJ@
CONST	SEGMENT
??_C@_0O@CDCMDCFE@?9?$CI?$CIx?$DM?$DNy?$CJ?$DPy?3x?$CJ@ DB '-((x<=y)?y:x)'
	DB	00H						; `string'
CONST	ENDS
;	COMDAT ??_C@_0BB@FKNPFCLB@sqrt?$CI?$CIx?$DM?$DNy?$CJ?$DPy?3x?$CJ@
CONST	SEGMENT
??_C@_0BB@FKNPFCLB@sqrt?$CI?$CIx?$DM?$DNy?$CJ?$DPy?3x?$CJ@ DB 'sqrt((x<=y'
	DB	')?y:x)', 00H				; `string'
CONST	ENDS
;	COMDAT ??_C@_0L@DJHLACHI@?$CIx?$DM?$DNy?$CJ?$DPy?3x@
CONST	SEGMENT
??_C@_0L@DJHLACHI@?$CIx?$DM?$DNy?$CJ?$DPy?3x@ DB '(x<=y)?y:x', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0CF@DNJEPAFA@x?5?$DN?5?$CL0?5?90?5nan?54?5?5?5?5?5y?5?$DN?5?90?5?$CL0?59@
CONST	SEGMENT
??_C@_0CF@DNJEPAFA@x?5?$DN?5?$CL0?5?90?5nan?54?5?5?5?5?5y?5?$DN?5?90?5?$CL0?59@ DB 'x'
	DB	' = +0 -0 nan 4     y = -0 +0 9 nan', 0aH, 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_01EEMJAFIK@?6@
CONST	SEGMENT
??_C@_01EEMJAFIK@?6@ DB 0aH, 00H			; `string'
CONST	ENDS
;	COMDAT ??_C@_05CNAAINAH@?5?$CFs?$CFg@
CONST	SEGMENT
??_C@_05CNAAINAH@?5?$CFs?$CFg@ DB ' %s%g', 00H		; `string'
CONST	ENDS
;	COMDAT ??_C@_00CNPNBAHC@@
CONST	SEGMENT
??_C@_00CNPNBAHC@@ DB 00H				; `string'
CONST	ENDS
;	COMDAT ??_C@_05HLLAPNIN@?$CF?946s@
CONST	SEGMENT
??_C@_05HLLAPNIN@?$CF?946s@ DB '%-46s', 00H		; `string'
CONST	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$main DD	010401H
	DD	0a204H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?show@@YAXPEBDPEBM@Z DD 020601H
	DD	030023206H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?signbit@@YA_NM@Z DD 010401H
	DD	04204H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$printf DD 041b01H
	DD	07017521bH
	DD	030156016H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$_vfprintf_l DD 081401H
	DD	0a6414H
	DD	095414H
	DD	083414H
	DD	070105214H
xdata	ENDS
; Function compile flags: /Ogtpy
; File D:\wsl\personal\dr\paper\toxic_compile\plan\reports_rewrites\msvc_blend\blend.cpp
;	COMDAT main
_TEXT	SEGMENT
o$ = 32
y$ = 48
x$ = 64
main	PROC						; COMDAT

; 36   : int main() {

$LN8:
	sub	rsp, 88					; 00000058H

; 37   :     const float nan = std::numeric_limits<float>::quiet_NaN();
; 38   :     float x[4] = {+0.0f, -0.0f, nan, 4.0f}, y[4] = {-0.0f, +0.0f, 9.0f, nan}, o[4];

	vmovdqu	xmm0, XMMWORD PTR __xmm@408000007fc000008000000000000000
	vmovdqu	xmm1, XMMWORD PTR __xmm@7fc00000411000000000000080000000

; 39   :     std::printf("x = +0 -0 nan 4     y = -0 +0 9 nan\n");

	lea	rcx, OFFSET FLAT:??_C@_0CF@DNJEPAFA@x?5?$DN?5?$CL0?5?90?5nan?54?5?5?5?5?5y?5?$DN?5?90?5?$CL0?59@
	vmovups	XMMWORD PTR x$[rsp], xmm0
	vmovups	XMMWORD PTR y$[rsp], xmm1
	call	printf

; 40   :     sel_only(x, y, o);         show("(x<=y)?y:x", o);

	lea	r8, QWORD PTR o$[rsp]
	lea	rdx, QWORD PTR y$[rsp]
	lea	rcx, QWORD PTR x$[rsp]
	call	?sel_only@@YAXPEBM0PEAM@Z		; sel_only
	lea	rdx, QWORD PTR o$[rsp]
	lea	rcx, OFFSET FLAT:??_C@_0L@DJHLACHI@?$CIx?$DM?$DNy?$CJ?$DPy?3x@
	call	?show@@YAXPEBDPEBM@Z			; show

; 41   :     sel_then_sqrt(x, y, o);    show("sqrt((x<=y)?y:x)", o);

	lea	r8, QWORD PTR o$[rsp]
	lea	rdx, QWORD PTR y$[rsp]
	lea	rcx, QWORD PTR x$[rsp]
	call	?sel_then_sqrt@@YAXPEBM0PEAM@Z		; sel_then_sqrt
	lea	rdx, QWORD PTR o$[rsp]
	lea	rcx, OFFSET FLAT:??_C@_0BB@FKNPFCLB@sqrt?$CI?$CIx?$DM?$DNy?$CJ?$DPy?3x?$CJ@
	call	?show@@YAXPEBDPEBM@Z			; show

; 42   :     sel_then_neg(x, y, o);     show("-((x<=y)?y:x)", o);

	lea	r8, QWORD PTR o$[rsp]
	lea	rdx, QWORD PTR y$[rsp]
	lea	rcx, QWORD PTR x$[rsp]
	call	?sel_then_neg@@YAXPEBM0PEAM@Z		; sel_then_neg
	lea	rdx, QWORD PTR o$[rsp]
	lea	rcx, OFFSET FLAT:??_C@_0O@CDCMDCFE@?9?$CI?$CIx?$DM?$DNy?$CJ?$DPy?3x?$CJ@
	call	?show@@YAXPEBDPEBM@Z			; show

; 43   :     sel_lt_then_sqrt(x, y, o); show("sqrt((x<y)?y:x)", o);

	lea	r8, QWORD PTR o$[rsp]
	lea	rdx, QWORD PTR y$[rsp]
	lea	rcx, QWORD PTR x$[rsp]
	call	?sel_lt_then_sqrt@@YAXPEBM0PEAM@Z	; sel_lt_then_sqrt
	lea	rdx, QWORD PTR o$[rsp]
	lea	rcx, OFFSET FLAT:??_C@_0BA@ENBOJJDF@sqrt?$CI?$CIx?$DMy?$CJ?$DPy?3x?$CJ@
	call	?show@@YAXPEBDPEBM@Z			; show

; 44   :     return 0;

	xor	eax, eax

; 45   : }

	add	rsp, 88					; 00000058H
	ret	0
main	ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File D:\wsl\personal\dr\paper\toxic_compile\plan\reports_rewrites\msvc_blend\blend.cpp
; File C:\Program Files (x86)\Windows Kits\10\include\10.0.26100.0\ucrt\corecrt_math.h
; File D:\wsl\personal\dr\paper\toxic_compile\plan\reports_rewrites\msvc_blend\blend.cpp
; File C:\Program Files (x86)\Windows Kits\10\include\10.0.26100.0\ucrt\corecrt_math.h
; File D:\wsl\personal\dr\paper\toxic_compile\plan\reports_rewrites\msvc_blend\blend.cpp
; File C:\Program Files (x86)\Windows Kits\10\include\10.0.26100.0\ucrt\corecrt_math.h
; File D:\wsl\personal\dr\paper\toxic_compile\plan\reports_rewrites\msvc_blend\blend.cpp
; File C:\Program Files (x86)\Windows Kits\10\include\10.0.26100.0\ucrt\corecrt_math.h
; File D:\wsl\personal\dr\paper\toxic_compile\plan\reports_rewrites\msvc_blend\blend.cpp
;	COMDAT ?show@@YAXPEBDPEBM@Z
_TEXT	SEGMENT
name$ = 48
o$ = 56
tv95 = 64
?show@@YAXPEBDPEBM@Z PROC				; show, COMDAT

; 30   : static void show(const char* name, const float* o) {

	push	rbx
	sub	rsp, 32					; 00000020H
	mov	rbx, rdx

; 31   :     std::printf("%-46s", name);

	mov	rdx, rcx
	lea	rcx, OFFSET FLAT:??_C@_05HLLAPNIN@?$CF?946s@
	call	printf
; File C:\Program Files (x86)\Windows Kits\10\include\10.0.26100.0\ucrt\corecrt_math.h

; 341  :         return _fdsign(_X) != 0;

	vmovss	xmm0, DWORD PTR [rbx]
	call	_fdsign
	vmovss	xmm2, DWORD PTR [rbx]
; File D:\wsl\personal\dr\paper\toxic_compile\plan\reports_rewrites\msvc_blend\blend.cpp

; 32   :     for (int i = 0; i < 4; ++i) std::printf(" %s%g", std::signbit(o[i]) && o[i] == 0 ? "" : "", o[i]);

	vcvtss2sd xmm2, xmm2, xmm2
	vmovq	r8, xmm2
	lea	rdx, OFFSET FLAT:??_C@_00CNPNBAHC@@
	lea	rcx, OFFSET FLAT:??_C@_05CNAAINAH@?5?$CFs?$CFg@
	call	printf
; File C:\Program Files (x86)\Windows Kits\10\include\10.0.26100.0\ucrt\corecrt_math.h

; 341  :         return _fdsign(_X) != 0;

	vmovss	xmm0, DWORD PTR [rbx+4]
	call	_fdsign
	vmovss	xmm2, DWORD PTR [rbx+4]
; File D:\wsl\personal\dr\paper\toxic_compile\plan\reports_rewrites\msvc_blend\blend.cpp

; 32   :     for (int i = 0; i < 4; ++i) std::printf(" %s%g", std::signbit(o[i]) && o[i] == 0 ? "" : "", o[i]);

	vcvtss2sd xmm2, xmm2, xmm2
	vmovq	r8, xmm2
	lea	rdx, OFFSET FLAT:??_C@_00CNPNBAHC@@
	lea	rcx, OFFSET FLAT:??_C@_05CNAAINAH@?5?$CFs?$CFg@
	call	printf
; File C:\Program Files (x86)\Windows Kits\10\include\10.0.26100.0\ucrt\corecrt_math.h

; 341  :         return _fdsign(_X) != 0;

	vmovss	xmm0, DWORD PTR [rbx+8]
	call	_fdsign
	vmovss	xmm2, DWORD PTR [rbx+8]
; File D:\wsl\personal\dr\paper\toxic_compile\plan\reports_rewrites\msvc_blend\blend.cpp

; 32   :     for (int i = 0; i < 4; ++i) std::printf(" %s%g", std::signbit(o[i]) && o[i] == 0 ? "" : "", o[i]);

	vcvtss2sd xmm2, xmm2, xmm2
	vmovq	r8, xmm2
	lea	rdx, OFFSET FLAT:??_C@_00CNPNBAHC@@
	lea	rcx, OFFSET FLAT:??_C@_05CNAAINAH@?5?$CFs?$CFg@
	call	printf
; File C:\Program Files (x86)\Windows Kits\10\include\10.0.26100.0\ucrt\corecrt_math.h

; 341  :         return _fdsign(_X) != 0;

	vmovss	xmm0, DWORD PTR [rbx+12]
	call	_fdsign
	vmovss	xmm2, DWORD PTR [rbx+12]
; File D:\wsl\personal\dr\paper\toxic_compile\plan\reports_rewrites\msvc_blend\blend.cpp

; 32   :     for (int i = 0; i < 4; ++i) std::printf(" %s%g", std::signbit(o[i]) && o[i] == 0 ? "" : "", o[i]);

	vcvtss2sd xmm2, xmm2, xmm2
	vmovq	r8, xmm2
	lea	rdx, OFFSET FLAT:??_C@_00CNPNBAHC@@
	lea	rcx, OFFSET FLAT:??_C@_05CNAAINAH@?5?$CFs?$CFg@
	call	printf

; 33   :     std::printf("\n");

	lea	rcx, OFFSET FLAT:??_C@_01EEMJAFIK@?6@

; 34   : }

	add	rsp, 32					; 00000020H
	pop	rbx

; 33   :     std::printf("\n");

	jmp	printf
?show@@YAXPEBDPEBM@Z ENDP				; show
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File D:\wsl\personal\dr\paper\toxic_compile\plan\reports_rewrites\msvc_blend\blend.cpp
;	COMDAT ?sel_lt_then_sqrt@@YAXPEBM0PEAM@Z
_TEXT	SEGMENT
px$ = 8
py$ = 16
po$ = 24
?sel_lt_then_sqrt@@YAXPEBM0PEAM@Z PROC			; sel_lt_then_sqrt, COMDAT

; 26   :     __m128 x = _mm_loadu_ps(px), y = _mm_loadu_ps(py);

	vmovups	xmm1, XMMWORD PTR [rdx]

; 27   :     _mm_storeu_ps(po, _mm_sqrt_ps(_mm_blendv_ps(x, y, _mm_cmp_ps(x, y, _CMP_LT_OS))));

	vmaxps	xmm1, xmm1, XMMWORD PTR [rcx]
	vsqrtps	xmm2, xmm1
	vmovups	XMMWORD PTR [r8], xmm2

; 28   : }

	ret	0
?sel_lt_then_sqrt@@YAXPEBM0PEAM@Z ENDP			; sel_lt_then_sqrt
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File D:\wsl\personal\dr\paper\toxic_compile\plan\reports_rewrites\msvc_blend\blend.cpp
;	COMDAT ?sel_then_neg@@YAXPEBM0PEAM@Z
_TEXT	SEGMENT
px$ = 8
py$ = 16
po$ = 24
?sel_then_neg@@YAXPEBM0PEAM@Z PROC			; sel_then_neg, COMDAT

; 22   :     __m128 x = _mm_loadu_ps(px), y = _mm_loadu_ps(py);

	vmovups	xmm1, XMMWORD PTR [rdx]

; 23   :     _mm_storeu_ps(po, _mm_xor_ps(_mm_blendv_ps(x, y, _mm_cmp_ps(x, y, _CMP_LE_OS)), _mm_set1_ps(-0.0f)));

	vmaxps	xmm2, xmm1, XMMWORD PTR [rcx]
	vxorps	xmm0, xmm2, XMMWORD PTR __xmm@80000000800000008000000080000000
	vmovups	XMMWORD PTR [r8], xmm0

; 24   : }

	ret	0
?sel_then_neg@@YAXPEBM0PEAM@Z ENDP			; sel_then_neg
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File D:\wsl\personal\dr\paper\toxic_compile\plan\reports_rewrites\msvc_blend\blend.cpp
;	COMDAT ?sel_then_sqrt@@YAXPEBM0PEAM@Z
_TEXT	SEGMENT
px$ = 8
py$ = 16
po$ = 24
?sel_then_sqrt@@YAXPEBM0PEAM@Z PROC			; sel_then_sqrt, COMDAT

; 18   :     __m128 x = _mm_loadu_ps(px), y = _mm_loadu_ps(py);

	vmovups	xmm1, XMMWORD PTR [rdx]

; 19   :     _mm_storeu_ps(po, _mm_sqrt_ps(_mm_blendv_ps(x, y, _mm_cmp_ps(x, y, _CMP_LE_OS))));

	vmaxps	xmm1, xmm1, XMMWORD PTR [rcx]
	vsqrtps	xmm2, xmm1
	vmovups	XMMWORD PTR [r8], xmm2

; 20   : }

	ret	0
?sel_then_sqrt@@YAXPEBM0PEAM@Z ENDP			; sel_then_sqrt
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File D:\wsl\personal\dr\paper\toxic_compile\plan\reports_rewrites\msvc_blend\blend.cpp
;	COMDAT ?sel_only@@YAXPEBM0PEAM@Z
_TEXT	SEGMENT
px$ = 8
py$ = 16
po$ = 24
?sel_only@@YAXPEBM0PEAM@Z PROC				; sel_only, COMDAT

; 14   :     __m128 x = _mm_loadu_ps(px), y = _mm_loadu_ps(py);

	vmovups	xmm1, XMMWORD PTR [rdx]

; 15   :     _mm_storeu_ps(po, _mm_blendv_ps(x, y, _mm_cmp_ps(x, y, _CMP_LE_OS)));          // (x <= y) ? y : x

	vmaxps	xmm1, xmm1, XMMWORD PTR [rcx]
	vmovups	XMMWORD PTR [r8], xmm1

; 16   : }

	ret	0
?sel_only@@YAXPEBM0PEAM@Z ENDP				; sel_only
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.44.35207\include\limits
;	COMDAT ?quiet_NaN@?$numeric_limits@M@std@@SAMXZ
_TEXT	SEGMENT
?quiet_NaN@?$numeric_limits@M@std@@SAMXZ PROC		; std::numeric_limits<float>::quiet_NaN, COMDAT

; 884  :         return __builtin_nanf("0");

	vmovss	xmm0, DWORD PTR __real@7fc00000

; 885  :     }

	ret	0
?quiet_NaN@?$numeric_limits@M@std@@SAMXZ ENDP		; std::numeric_limits<float>::quiet_NaN
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File C:\Program Files (x86)\Windows Kits\10\include\10.0.26100.0\ucrt\corecrt_math.h
;	COMDAT ?signbit@@YA_NM@Z
_TEXT	SEGMENT
_X$ = 48
?signbit@@YA_NM@Z PROC					; signbit, COMDAT

; 340  :     {

$LN4:
	sub	rsp, 40					; 00000028H

; 341  :         return _fdsign(_X) != 0;

	call	_fdsign
	test	eax, eax
	setne	al

; 342  :     }

	add	rsp, 40					; 00000028H
	ret	0
?signbit@@YA_NM@Z ENDP					; signbit
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File C:\Program Files (x86)\Windows Kits\10\include\10.0.26100.0\ucrt\stdio.h
;	COMDAT printf
_TEXT	SEGMENT
_Format$ = 80
printf	PROC						; COMDAT

; 956  :     {

$LN6:
	mov	QWORD PTR [rsp+8], rcx
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+24], r8
	mov	QWORD PTR [rsp+32], r9
	push	rbx
	push	rsi
	push	rdi
	sub	rsp, 48					; 00000030H
	mov	rdi, rcx

; 957  :         int _Result;
; 958  :         va_list _ArgList;
; 959  :         __crt_va_start(_ArgList, _Format);

	lea	rsi, QWORD PTR _Format$[rsp+8]

; 960  :         _Result = _vfprintf_l(stdout, _Format, NULL, _ArgList);

	mov	ecx, 1
	call	__acrt_iob_func
	mov	rbx, rax

; 645  :         return __stdio_common_vfprintf(_CRT_INTERNAL_LOCAL_PRINTF_OPTIONS, _Stream, _Format, _Locale, _ArgList);

	call	__local_stdio_printf_options
	xor	r9d, r9d
	mov	QWORD PTR [rsp+32], rsi
	mov	r8, rdi
	mov	rdx, rbx
	mov	rcx, QWORD PTR [rax]
	call	__stdio_common_vfprintf

; 961  :         __crt_va_end(_ArgList);
; 962  :         return _Result;
; 963  :     }

	add	rsp, 48					; 00000030H
	pop	rdi
	pop	rsi
	pop	rbx
	ret	0
printf	ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File C:\Program Files (x86)\Windows Kits\10\include\10.0.26100.0\ucrt\stdio.h
;	COMDAT _vfprintf_l
_TEXT	SEGMENT
_Stream$ = 64
_Format$ = 72
_Locale$ = 80
_ArgList$ = 88
_vfprintf_l PROC					; COMDAT

; 644  :     {

$LN4:
	mov	QWORD PTR [rsp+8], rbx
	mov	QWORD PTR [rsp+16], rbp
	mov	QWORD PTR [rsp+24], rsi
	push	rdi
	sub	rsp, 48					; 00000030H
	mov	rbx, r9
	mov	rdi, r8
	mov	rsi, rdx
	mov	rbp, rcx

; 645  :         return __stdio_common_vfprintf(_CRT_INTERNAL_LOCAL_PRINTF_OPTIONS, _Stream, _Format, _Locale, _ArgList);

	call	__local_stdio_printf_options
	mov	r9, rdi
	mov	QWORD PTR [rsp+32], rbx
	mov	r8, rsi
	mov	rdx, rbp
	mov	rcx, QWORD PTR [rax]
	call	__stdio_common_vfprintf

; 646  :     }

	mov	rbx, QWORD PTR [rsp+64]
	mov	rbp, QWORD PTR [rsp+72]
	mov	rsi, QWORD PTR [rsp+80]
	add	rsp, 48					; 00000030H
	pop	rdi
	ret	0
_vfprintf_l ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File C:\Program Files (x86)\Windows Kits\10\include\10.0.26100.0\ucrt\corecrt_stdio_config.h
;	COMDAT __local_stdio_printf_options
_TEXT	SEGMENT
__local_stdio_printf_options PROC			; COMDAT

; 91   :         static unsigned __int64 _OptionsStorage;
; 92   :         return &_OptionsStorage;

	lea	rax, OFFSET FLAT:?_OptionsStorage@?1??__local_stdio_printf_options@@9@4_KA ; `__local_stdio_printf_options'::`2'::_OptionsStorage

; 93   :     }

	ret	0
__local_stdio_printf_options ENDP
_TEXT	ENDS
END
