; Listing generated by Microsoft (R) Optimizing Compiler Version 19.44.35228.0 

include listing.inc

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	__local_stdio_printf_options
PUBLIC	_vfprintf_l
PUBLIC	printf
PUBLIC	?abs1_256@@YAXPEBHPEAH@Z			; abs1_256
PUBLIC	?abs2_256@@YAXPEBHPEAH@Z			; abs2_256
PUBLIC	?abs3_256@@YAXPEBHPEAH@Z			; abs3_256
PUBLIC	?abs2_128@@YAXPEBHPEAH@Z			; abs2_128
PUBLIC	?abs2_256_i8@@YAXPEBCPEAC@Z			; abs2_256_i8
PUBLIC	main
PUBLIC	?_OptionsStorage@?1??__local_stdio_printf_options@@9@4_KA ; `__local_stdio_printf_options'::`2'::_OptionsStorage
PUBLIC	??_C@_05FEEFIPFL@?$CF?928s@			; `string'
PUBLIC	??_C@_03EBJOKFHF@?5?$CFd@			; `string'
PUBLIC	??_C@_01EEMJAFIK@?6@				; `string'
PUBLIC	??_C@_05DFJCHPDH@input@				; `string'
PUBLIC	??_C@_0BF@BINOGALI@abs?5?5?5?5?5?5?5?5?5?5?5?5?$CI256?$CJ@ ; `string'
PUBLIC	??_C@_0BF@ENADMCJB@abs?$CIabs?$CJ?5?5?5?5?5?5?5?$CI256?$CJ@ ; `string'
PUBLIC	??_C@_0BF@NNKFGEBC@abs?$CIabs?$CIabs?$CJ?$CJ?5?5?$CI256?$CJ@ ; `string'
PUBLIC	??_C@_0BF@JNOKKNPC@abs?$CIabs?$CJ?5?5?5?5?5?5?5?$CI128?$CJ@ ; `string'
PUBLIC	??_C@_0BF@MDBALLEC@abs?$CIabs?$CJ?5int8?5?5?$CI256?$CJ@ ; `string'
PUBLIC	__ymm@0000000700000006000000050000000400000003000000020000000100000000
PUBLIC	__ymm@0808080808080808080808080808080808080808080808080808080808080808
PUBLIC	__ymm@1f1e1d1c1b1a191817161514131211100f0e0d0c0b0a09080706050403020100
PUBLIC	__ymm@fffffffffffffffefffffffdfffffffcfffffffbfffffffafffffff9fffffff8
EXTRN	__acrt_iob_func:PROC
EXTRN	__stdio_common_vfprintf:PROC
EXTRN	__GSHandlerCheck:PROC
EXTRN	__security_check_cookie:PROC
EXTRN	__security_cookie:QWORD
;	COMDAT ?_OptionsStorage@?1??__local_stdio_printf_options@@9@4_KA
_BSS	SEGMENT
?_OptionsStorage@?1??__local_stdio_printf_options@@9@4_KA DQ 01H DUP (?) ; `__local_stdio_printf_options'::`2'::_OptionsStorage
_BSS	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$_vfprintf_l DD imagerel $LN4
	DD	imagerel $LN4+80
	DD	imagerel $unwind$_vfprintf_l
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$printf DD imagerel $LN6
	DD	imagerel $LN6+83
	DD	imagerel $unwind$printf
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?show@@YAXPEBDPEBHH@Z DD imagerel ?show@@YAXPEBDPEBHH@Z
	DD	imagerel ?show@@YAXPEBDPEBHH@Z+98
	DD	imagerel $unwind$?show@@YAXPEBDPEBHH@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$main DD	imagerel $LN92
	DD	imagerel $LN92+585
	DD	imagerel $unwind$main
pdata	ENDS
;	COMDAT __ymm@fffffffffffffffefffffffdfffffffcfffffffbfffffffafffffff9fffffff8
CONST	SEGMENT
__ymm@fffffffffffffffefffffffdfffffffcfffffffbfffffffafffffff9fffffff8 DB 0f8H
	DB	0ffH, 0ffH, 0ffH, 0f9H, 0ffH, 0ffH, 0ffH, 0faH, 0ffH, 0ffH, 0ffH
	DB	0fbH, 0ffH, 0ffH, 0ffH, 0fcH, 0ffH, 0ffH, 0ffH, 0fdH, 0ffH, 0ffH
	DB	0ffH, 0feH, 0ffH, 0ffH, 0ffH, 0ffH, 0ffH, 0ffH, 0ffH
CONST	ENDS
;	COMDAT __ymm@1f1e1d1c1b1a191817161514131211100f0e0d0c0b0a09080706050403020100
CONST	SEGMENT
__ymm@1f1e1d1c1b1a191817161514131211100f0e0d0c0b0a09080706050403020100 DB 00H
	DB	01H, 02H, 03H, 04H, 05H, 06H, 07H, 08H, 09H, 0aH, 0bH, 0cH, 0dH
	DB	0eH, 0fH, 010H, 011H, 012H, 013H, 014H, 015H, 016H, 017H, 018H
	DB	019H, 01aH, 01bH, 01cH, 01dH, 01eH, 01fH
CONST	ENDS
;	COMDAT __ymm@0808080808080808080808080808080808080808080808080808080808080808
CONST	SEGMENT
__ymm@0808080808080808080808080808080808080808080808080808080808080808 DB 08H
	DB	08H, 08H, 08H, 08H, 08H, 08H, 08H, 08H, 08H, 08H, 08H, 08H, 08H
	DB	08H, 08H, 08H, 08H, 08H, 08H, 08H, 08H, 08H, 08H, 08H, 08H, 08H
	DB	08H, 08H, 08H, 08H, 08H
CONST	ENDS
;	COMDAT __ymm@0000000700000006000000050000000400000003000000020000000100000000
CONST	SEGMENT
__ymm@0000000700000006000000050000000400000003000000020000000100000000 DB 00H
	DB	00H, 00H, 00H, 01H, 00H, 00H, 00H, 02H, 00H, 00H, 00H, 03H, 00H
	DB	00H, 00H, 04H, 00H, 00H, 00H, 05H, 00H, 00H, 00H, 06H, 00H, 00H
	DB	00H, 07H, 00H, 00H, 00H
CONST	ENDS
;	COMDAT ??_C@_0BF@MDBALLEC@abs?$CIabs?$CJ?5int8?5?5?$CI256?$CJ@
CONST	SEGMENT
??_C@_0BF@MDBALLEC@abs?$CIabs?$CJ?5int8?5?5?$CI256?$CJ@ DB 'abs(abs) int8'
	DB	'  (256)', 00H				; `string'
CONST	ENDS
;	COMDAT ??_C@_0BF@JNOKKNPC@abs?$CIabs?$CJ?5?5?5?5?5?5?5?$CI128?$CJ@
CONST	SEGMENT
??_C@_0BF@JNOKKNPC@abs?$CIabs?$CJ?5?5?5?5?5?5?5?$CI128?$CJ@ DB 'abs(abs) '
	DB	'      (128)', 00H				; `string'
CONST	ENDS
;	COMDAT ??_C@_0BF@NNKFGEBC@abs?$CIabs?$CIabs?$CJ?$CJ?5?5?$CI256?$CJ@
CONST	SEGMENT
??_C@_0BF@NNKFGEBC@abs?$CIabs?$CIabs?$CJ?$CJ?5?5?$CI256?$CJ@ DB 'abs(abs('
	DB	'abs))  (256)', 00H				; `string'
CONST	ENDS
;	COMDAT ??_C@_0BF@ENADMCJB@abs?$CIabs?$CJ?5?5?5?5?5?5?5?$CI256?$CJ@
CONST	SEGMENT
??_C@_0BF@ENADMCJB@abs?$CIabs?$CJ?5?5?5?5?5?5?5?$CI256?$CJ@ DB 'abs(abs) '
	DB	'      (256)', 00H				; `string'
CONST	ENDS
;	COMDAT ??_C@_0BF@BINOGALI@abs?5?5?5?5?5?5?5?5?5?5?5?5?$CI256?$CJ@
CONST	SEGMENT
??_C@_0BF@BINOGALI@abs?5?5?5?5?5?5?5?5?5?5?5?5?$CI256?$CJ@ DB 'abs       '
	DB	'     (256)', 00H				; `string'
CONST	ENDS
;	COMDAT ??_C@_05DFJCHPDH@input@
CONST	SEGMENT
??_C@_05DFJCHPDH@input@ DB 'input', 00H			; `string'
CONST	ENDS
;	COMDAT ??_C@_01EEMJAFIK@?6@
CONST	SEGMENT
??_C@_01EEMJAFIK@?6@ DB 0aH, 00H			; `string'
CONST	ENDS
;	COMDAT ??_C@_03EBJOKFHF@?5?$CFd@
CONST	SEGMENT
??_C@_03EBJOKFHF@?5?$CFd@ DB ' %d', 00H			; `string'
CONST	ENDS
;	COMDAT ??_C@_05FEEFIPFL@?$CF?928s@
CONST	SEGMENT
??_C@_05FEEFIPFL@?$CF?928s@ DB '%-28s', 00H		; `string'
CONST	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$main DD	051f19H
	DD	018340dH
	DD	016010dH
	DD	07006H
	DD	imagerel __GSHandlerCheck
	DD	0a0H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?show@@YAXPEBDPEBHH@Z DD 060f01H
	DD	07640fH
	DD	06340fH
	DD	0700b320fH
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$printf DD 041b01H
	DD	07017521bH
	DD	030156016H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$_vfprintf_l DD 081401H
	DD	0a6414H
	DD	095414H
	DD	083414H
	DD	070105214H
xdata	ENDS
; Function compile flags: /Ogtpy
; File D:\wsl\personal\dr\paper\toxic_compile\plan\reports_rewrites\msvc_abs\abs_abs.cpp
;	COMDAT main
_TEXT	SEGMENT
in$ = 32
in8$ = 32
out$ = 96
out8$ = 96
__$ArrayPad$ = 160
main	PROC						; COMDAT

; 45   : int main() {

$LN92:
	mov	QWORD PTR [rsp+8], rbx
	push	rdi
	sub	rsp, 176				; 000000b0H
	mov	rax, QWORD PTR __security_cookie
	xor	rax, rsp
	mov	QWORD PTR __$ArrayPad$[rsp], rax

; 46   :     int32_t in[16], out[16];
; 47   :     for (int i = 0; i < 16; ++i) in[i] = i - 8;

	vmovdqu	ymm0, YMMWORD PTR __ymm@fffffffffffffffefffffffdfffffffcfffffffbfffffffafffffff9fffffff8
	vmovdqu	ymm1, YMMWORD PTR __ymm@0000000700000006000000050000000400000003000000020000000100000000
	vmovdqu	YMMWORD PTR in$[rsp], ymm0
	vmovdqu	YMMWORD PTR in$[rsp+32], ymm1

; 40   :     std::printf("%-28s", name);

	lea	rdx, OFFSET FLAT:??_C@_05DFJCHPDH@input@
	lea	rcx, OFFSET FLAT:??_C@_05FEEFIPFL@?$CF?928s@
	vzeroupper
	call	printf
	xor	ebx, ebx
	mov	edi, ebx
	npad	11
$LL15@main:

; 41   :     for (int i = 0; i < n; ++i) std::printf(" %d", o[i]);

	mov	edx, DWORD PTR in$[rsp+rdi*4]
	lea	rcx, OFFSET FLAT:??_C@_03EBJOKFHF@?5?$CFd@
	call	printf
	inc	rdi
	cmp	rdi, 8
	jl	SHORT $LL15@main

; 42   :     std::printf("\n");

	lea	rcx, OFFSET FLAT:??_C@_01EEMJAFIK@?6@
	call	printf

; 48   :     show("input", in, 8);
; 49   :     abs1_256(in, out); show("abs            (256)", out, 8);

	lea	rdx, QWORD PTR out$[rsp]
	lea	rcx, QWORD PTR in$[rsp]
	call	?abs1_256@@YAXPEBHPEAH@Z		; abs1_256

; 40   :     std::printf("%-28s", name);

	lea	rdx, OFFSET FLAT:??_C@_0BF@BINOGALI@abs?5?5?5?5?5?5?5?5?5?5?5?5?$CI256?$CJ@
	lea	rcx, OFFSET FLAT:??_C@_05FEEFIPFL@?$CF?928s@
	call	printf
	mov	rdi, rbx
	npad	6
$LL20@main:

; 41   :     for (int i = 0; i < n; ++i) std::printf(" %d", o[i]);

	mov	edx, DWORD PTR out$[rsp+rdi*4]
	lea	rcx, OFFSET FLAT:??_C@_03EBJOKFHF@?5?$CFd@
	call	printf
	inc	rdi
	cmp	rdi, 8
	jl	SHORT $LL20@main

; 42   :     std::printf("\n");

	lea	rcx, OFFSET FLAT:??_C@_01EEMJAFIK@?6@
	call	printf

; 50   :     abs2_256(in, out); show("abs(abs)       (256)", out, 8);

	lea	rdx, QWORD PTR out$[rsp]
	lea	rcx, QWORD PTR in$[rsp]
	call	?abs2_256@@YAXPEBHPEAH@Z		; abs2_256

; 40   :     std::printf("%-28s", name);

	lea	rdx, OFFSET FLAT:??_C@_0BF@ENADMCJB@abs?$CIabs?$CJ?5?5?5?5?5?5?5?$CI256?$CJ@
	lea	rcx, OFFSET FLAT:??_C@_05FEEFIPFL@?$CF?928s@
	call	printf
	mov	rdi, rbx
	npad	6
$LL25@main:

; 41   :     for (int i = 0; i < n; ++i) std::printf(" %d", o[i]);

	mov	edx, DWORD PTR out$[rsp+rdi*4]
	lea	rcx, OFFSET FLAT:??_C@_03EBJOKFHF@?5?$CFd@
	call	printf
	inc	rdi
	cmp	rdi, 8
	jl	SHORT $LL25@main

; 42   :     std::printf("\n");

	lea	rcx, OFFSET FLAT:??_C@_01EEMJAFIK@?6@
	call	printf

; 51   :     abs3_256(in, out); show("abs(abs(abs))  (256)", out, 8);

	lea	rdx, QWORD PTR out$[rsp]
	lea	rcx, QWORD PTR in$[rsp]
	call	?abs3_256@@YAXPEBHPEAH@Z		; abs3_256

; 40   :     std::printf("%-28s", name);

	lea	rdx, OFFSET FLAT:??_C@_0BF@NNKFGEBC@abs?$CIabs?$CIabs?$CJ?$CJ?5?5?$CI256?$CJ@
	lea	rcx, OFFSET FLAT:??_C@_05FEEFIPFL@?$CF?928s@
	call	printf
	mov	rdi, rbx
	npad	6
$LL30@main:

; 41   :     for (int i = 0; i < n; ++i) std::printf(" %d", o[i]);

	mov	edx, DWORD PTR out$[rsp+rdi*4]
	lea	rcx, OFFSET FLAT:??_C@_03EBJOKFHF@?5?$CFd@
	call	printf
	inc	rdi
	cmp	rdi, 8
	jl	SHORT $LL30@main

; 42   :     std::printf("\n");

	lea	rcx, OFFSET FLAT:??_C@_01EEMJAFIK@?6@
	call	printf

; 52   :     abs2_128(in, out); show("abs(abs)       (128)", out, 4);

	lea	rdx, QWORD PTR out$[rsp]
	lea	rcx, QWORD PTR in$[rsp]
	call	?abs2_128@@YAXPEBHPEAH@Z		; abs2_128

; 40   :     std::printf("%-28s", name);

	lea	rdx, OFFSET FLAT:??_C@_0BF@JNOKKNPC@abs?$CIabs?$CJ?5?5?5?5?5?5?5?$CI128?$CJ@
	lea	rcx, OFFSET FLAT:??_C@_05FEEFIPFL@?$CF?928s@
	call	printf
	mov	rdi, rbx
	npad	6
$LL35@main:

; 41   :     for (int i = 0; i < n; ++i) std::printf(" %d", o[i]);

	mov	edx, DWORD PTR out$[rsp+rdi*4]
	lea	rcx, OFFSET FLAT:??_C@_03EBJOKFHF@?5?$CFd@
	call	printf
	inc	rdi
	cmp	rdi, 4
	jl	SHORT $LL35@main

; 42   :     std::printf("\n");

	lea	rcx, OFFSET FLAT:??_C@_01EEMJAFIK@?6@
	call	printf

; 53   : #ifdef __AVX512F__
; 54   :     abs2_512(in, out); show("abs(abs)       (512)", out, 8);
; 55   : #endif
; 56   :     int8_t in8[32], out8[32];
; 57   :     for (int i = 0; i < 32; ++i) in8[i] = (int8_t)(i - 8);

	vmovaps	ymm1, YMMWORD PTR __ymm@1f1e1d1c1b1a191817161514131211100f0e0d0c0b0a09080706050403020100
	vpsubb	ymm1, ymm1, YMMWORD PTR __ymm@0808080808080808080808080808080808080808080808080808080808080808
	vmovups	YMMWORD PTR in8$[rsp], ymm1

; 58   :     abs2_256_i8(in8, out8);

	lea	rdx, QWORD PTR out8$[rsp]
	lea	rcx, QWORD PTR in8$[rsp]
	vzeroupper
	call	?abs2_256_i8@@YAXPEBCPEAC@Z		; abs2_256_i8

; 59   :     std::printf("%-28s", "abs(abs) int8  (256)");

	lea	rdx, OFFSET FLAT:??_C@_0BF@MDBALLEC@abs?$CIabs?$CJ?5int8?5?5?$CI256?$CJ@
	lea	rcx, OFFSET FLAT:??_C@_05FEEFIPFL@?$CF?928s@
	call	printf
$LL10@main:

; 60   :     for (int i = 0; i < 8; ++i) std::printf(" %d", out8[i]);

	movsx	edx, BYTE PTR out8$[rsp+rbx]
	lea	rcx, OFFSET FLAT:??_C@_03EBJOKFHF@?5?$CFd@
	call	printf
	inc	rbx
	cmp	rbx, 8
	jl	SHORT $LL10@main

; 61   :     std::printf("\n");

	lea	rcx, OFFSET FLAT:??_C@_01EEMJAFIK@?6@
	call	printf

; 62   :     return 0;

	xor	eax, eax

; 63   : }

	mov	rcx, QWORD PTR __$ArrayPad$[rsp]
	xor	rcx, rsp
	call	__security_check_cookie
	mov	rbx, QWORD PTR [rsp+192]
	add	rsp, 176				; 000000b0H
	pop	rdi
	ret	0
main	ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File D:\wsl\personal\dr\paper\toxic_compile\plan\reports_rewrites\msvc_abs\abs_abs.cpp
;	COMDAT ?show@@YAXPEBDPEBHH@Z
_TEXT	SEGMENT
name$ = 48
o$ = 56
n$ = 64
?show@@YAXPEBDPEBHH@Z PROC				; show, COMDAT

; 39   : static void show(const char* name, const int32_t* o, int n) {

	mov	QWORD PTR [rsp+8], rbx
	mov	QWORD PTR [rsp+16], rsi
	push	rdi
	sub	rsp, 32					; 00000020H
	mov	rsi, rdx
	movsxd	rbx, r8d

; 40   :     std::printf("%-28s", name);

	mov	rdx, rcx
	lea	rcx, OFFSET FLAT:??_C@_05FEEFIPFL@?$CF?928s@
	call	printf

; 41   :     for (int i = 0; i < n; ++i) std::printf(" %d", o[i]);

	mov	rdi, rbx
	test	ebx, ebx
	jle	SHORT $LN3@show
	xor	ebx, ebx
	npad	3
$LL4@show:
	mov	edx, DWORD PTR [rsi+rbx*4]
	lea	rcx, OFFSET FLAT:??_C@_03EBJOKFHF@?5?$CFd@
	call	printf
	inc	rbx
	cmp	rbx, rdi
	jl	SHORT $LL4@show
$LN3@show:

; 42   :     std::printf("\n");

	lea	rcx, OFFSET FLAT:??_C@_01EEMJAFIK@?6@

; 43   : }

	mov	rbx, QWORD PTR [rsp+48]
	mov	rsi, QWORD PTR [rsp+56]
	add	rsp, 32					; 00000020H
	pop	rdi

; 42   :     std::printf("\n");

	jmp	printf
?show@@YAXPEBDPEBHH@Z ENDP				; show
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File D:\wsl\personal\dr\paper\toxic_compile\plan\reports_rewrites\msvc_abs\abs_abs.cpp
;	COMDAT ?abs2_256_i8@@YAXPEBCPEAC@Z
_TEXT	SEGMENT
in$ = 8
out$ = 16
?abs2_256_i8@@YAXPEBCPEAC@Z PROC			; abs2_256_i8, COMDAT

; 29   :     __m256i v = _mm256_loadu_si256((const __m256i*)in);
; 30   :     _mm256_storeu_si256((__m256i*)out, _mm256_abs_epi8(_mm256_abs_epi8(v)));

	vmovdqu	ymm0, YMMWORD PTR [rcx]
	vmovdqu	YMMWORD PTR [rdx], ymm0
	vzeroupper

; 31   : }

	ret	0
?abs2_256_i8@@YAXPEBCPEAC@Z ENDP			; abs2_256_i8
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File D:\wsl\personal\dr\paper\toxic_compile\plan\reports_rewrites\msvc_abs\abs_abs.cpp
;	COMDAT ?abs2_128@@YAXPEBHPEAH@Z
_TEXT	SEGMENT
in$ = 8
out$ = 16
?abs2_128@@YAXPEBHPEAH@Z PROC				; abs2_128, COMDAT

; 25   :     __m128i v = _mm_loadu_si128((const __m128i*)in);
; 26   :     _mm_storeu_si128((__m128i*)out, _mm_abs_epi32(_mm_abs_epi32(v)));

	vmovdqu	xmm0, XMMWORD PTR [rcx]
	vmovdqu	XMMWORD PTR [rdx], xmm0

; 27   : }

	ret	0
?abs2_128@@YAXPEBHPEAH@Z ENDP				; abs2_128
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File D:\wsl\personal\dr\paper\toxic_compile\plan\reports_rewrites\msvc_abs\abs_abs.cpp
;	COMDAT ?abs3_256@@YAXPEBHPEAH@Z
_TEXT	SEGMENT
in$ = 8
out$ = 16
?abs3_256@@YAXPEBHPEAH@Z PROC				; abs3_256, COMDAT

; 21   :     __m256i v = _mm256_loadu_si256((const __m256i*)in);
; 22   :     _mm256_storeu_si256((__m256i*)out, _mm256_abs_epi32(_mm256_abs_epi32(_mm256_abs_epi32(v))));

	vpabsd	ymm1, YMMWORD PTR [rcx]
	vmovdqu	YMMWORD PTR [rdx], ymm1
	vzeroupper

; 23   : }

	ret	0
?abs3_256@@YAXPEBHPEAH@Z ENDP				; abs3_256
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File D:\wsl\personal\dr\paper\toxic_compile\plan\reports_rewrites\msvc_abs\abs_abs.cpp
;	COMDAT ?abs2_256@@YAXPEBHPEAH@Z
_TEXT	SEGMENT
in$ = 8
out$ = 16
?abs2_256@@YAXPEBHPEAH@Z PROC				; abs2_256, COMDAT

; 17   :     __m256i v = _mm256_loadu_si256((const __m256i*)in);
; 18   :     _mm256_storeu_si256((__m256i*)out, _mm256_abs_epi32(_mm256_abs_epi32(v)));

	vmovdqu	ymm0, YMMWORD PTR [rcx]
	vmovdqu	YMMWORD PTR [rdx], ymm0
	vzeroupper

; 19   : }

	ret	0
?abs2_256@@YAXPEBHPEAH@Z ENDP				; abs2_256
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File D:\wsl\personal\dr\paper\toxic_compile\plan\reports_rewrites\msvc_abs\abs_abs.cpp
;	COMDAT ?abs1_256@@YAXPEBHPEAH@Z
_TEXT	SEGMENT
in$ = 8
out$ = 16
?abs1_256@@YAXPEBHPEAH@Z PROC				; abs1_256, COMDAT

; 13   :     __m256i v = _mm256_loadu_si256((const __m256i*)in);
; 14   :     _mm256_storeu_si256((__m256i*)out, _mm256_abs_epi32(v));

	vpabsd	ymm0, YMMWORD PTR [rcx]
	vmovdqu	YMMWORD PTR [rdx], ymm0
	vzeroupper

; 15   : }

	ret	0
?abs1_256@@YAXPEBHPEAH@Z ENDP				; abs1_256
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File C:\Program Files (x86)\Windows Kits\10\include\10.0.26100.0\ucrt\stdio.h
;	COMDAT printf
_TEXT	SEGMENT
_Format$ = 80
printf	PROC						; COMDAT

; 956  :     {

$LN6:
	mov	QWORD PTR [rsp+8], rcx
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+24], r8
	mov	QWORD PTR [rsp+32], r9
	push	rbx
	push	rsi
	push	rdi
	sub	rsp, 48					; 00000030H
	mov	rdi, rcx

; 957  :         int _Result;
; 958  :         va_list _ArgList;
; 959  :         __crt_va_start(_ArgList, _Format);

	lea	rsi, QWORD PTR _Format$[rsp+8]

; 960  :         _Result = _vfprintf_l(stdout, _Format, NULL, _ArgList);

	mov	ecx, 1
	call	__acrt_iob_func
	mov	rbx, rax

; 645  :         return __stdio_common_vfprintf(_CRT_INTERNAL_LOCAL_PRINTF_OPTIONS, _Stream, _Format, _Locale, _ArgList);

	call	__local_stdio_printf_options
	xor	r9d, r9d
	mov	QWORD PTR [rsp+32], rsi
	mov	r8, rdi
	mov	rdx, rbx
	mov	rcx, QWORD PTR [rax]
	call	__stdio_common_vfprintf

; 961  :         __crt_va_end(_ArgList);
; 962  :         return _Result;
; 963  :     }

	add	rsp, 48					; 00000030H
	pop	rdi
	pop	rsi
	pop	rbx
	ret	0
printf	ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File C:\Program Files (x86)\Windows Kits\10\include\10.0.26100.0\ucrt\stdio.h
;	COMDAT _vfprintf_l
_TEXT	SEGMENT
_Stream$ = 64
_Format$ = 72
_Locale$ = 80
_ArgList$ = 88
_vfprintf_l PROC					; COMDAT

; 644  :     {

$LN4:
	mov	QWORD PTR [rsp+8], rbx
	mov	QWORD PTR [rsp+16], rbp
	mov	QWORD PTR [rsp+24], rsi
	push	rdi
	sub	rsp, 48					; 00000030H
	mov	rbx, r9
	mov	rdi, r8
	mov	rsi, rdx
	mov	rbp, rcx

; 645  :         return __stdio_common_vfprintf(_CRT_INTERNAL_LOCAL_PRINTF_OPTIONS, _Stream, _Format, _Locale, _ArgList);

	call	__local_stdio_printf_options
	mov	r9, rdi
	mov	QWORD PTR [rsp+32], rbx
	mov	r8, rsi
	mov	rdx, rbp
	mov	rcx, QWORD PTR [rax]
	call	__stdio_common_vfprintf

; 646  :     }

	mov	rbx, QWORD PTR [rsp+64]
	mov	rbp, QWORD PTR [rsp+72]
	mov	rsi, QWORD PTR [rsp+80]
	add	rsp, 48					; 00000030H
	pop	rdi
	ret	0
_vfprintf_l ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File C:\Program Files (x86)\Windows Kits\10\include\10.0.26100.0\ucrt\corecrt_stdio_config.h
;	COMDAT __local_stdio_printf_options
_TEXT	SEGMENT
__local_stdio_printf_options PROC			; COMDAT

; 91   :         static unsigned __int64 _OptionsStorage;
; 92   :         return &_OptionsStorage;

	lea	rax, OFFSET FLAT:?_OptionsStorage@?1??__local_stdio_printf_options@@9@4_KA ; `__local_stdio_printf_options'::`2'::_OptionsStorage

; 93   :     }

	ret	0
__local_stdio_printf_options ENDP
_TEXT	ENDS
END
