; Listing generated by Microsoft (R) Optimizing Compiler Version 19.44.35228.0 

include listing.inc

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	__local_stdio_printf_options
PUBLIC	_vfprintf_l
PUBLIC	printf
PUBLIC	?signbit@@YA_NN@Z				; signbit
PUBLIC	?scalar_f@@YAMM@Z				; scalar_f
PUBLIC	?scalar_d@@YANN@Z				; scalar_d
PUBLIC	?sse_ps@@YAXPEBMPEAM@Z				; sse_ps
PUBLIC	?sse_ps_set1@@YAXPEBMPEAM@Z			; sse_ps_set1
PUBLIC	?avx_ps@@YAXPEBMPEAM@Z				; avx_ps
PUBLIC	?avx_pd@@YAXPEBNPEAN@Z				; avx_pd
PUBLIC	?avx_ps_rev@@YAXPEBMPEAM@Z			; avx_ps_rev
PUBLIC	?avx_ps_sub@@YAXPEBMPEAM@Z			; avx_ps_sub
PUBLIC	main
PUBLIC	?_OptionsStorage@?1??__local_stdio_printf_options@@9@4_KA ; `__local_stdio_printf_options'::`2'::_OptionsStorage
PUBLIC	??_C@_02OPGNMFKN@?90@				; `string'
PUBLIC	??_C@_02OLOALJBP@?$CL0@				; `string'
PUBLIC	??_C@_0CJ@MBAAFMLA@scalar?5float?5?5?5?90?40f?5?$CL?50?40f?5?5?5?5@ ; `string'
PUBLIC	??_C@_0CJ@FMEPFAPL@scalar?5double?5?5?90?40?5?5?$CL?50?40?5?5?5?5?5@ ; `string'
PUBLIC	??_C@_0CM@KAFIMPEB@_mm_add_ps?$CIx?0?5_mm_setzero_ps?$CI?$CJ?$CJ@ ; `string'
PUBLIC	??_C@_0CM@OOIHBKIE@_mm_add_ps?$CIx?0?5_mm_set1_ps?$CI0?40f?$CJ@ ; `string'
PUBLIC	??_C@_0CM@KJNJIOFI@_mm256_add_ps?$CIx?0?5_mm256_setzero@ ; `string'
PUBLIC	??_C@_0CM@LCGOOMG@_mm256_add_ps?$CI_mm256_setzero_ps@ ; `string'
PUBLIC	??_C@_0CM@ILNICDGM@_mm256_add_pd?$CIx?0?5_mm256_setzero@ ; `string'
PUBLIC	??_C@_0CM@JPKPIEDH@_mm256_sub_ps?$CIx?0?5set1?$CI?90?40f?$CJ?$CJ?5?5@ ; `string'
PUBLIC	__real@80000000
PUBLIC	__real@8000000000000000
PUBLIC	__xmm@80000000000000008000000000000000
PUBLIC	__xmm@80000000800000008000000080000000
PUBLIC	__ymm@8000000080000000800000008000000080000000800000008000000080000000
EXTRN	__acrt_iob_func:PROC
EXTRN	__stdio_common_vfprintf:PROC
EXTRN	_dsign:PROC
EXTRN	__GSHandlerCheck:PROC
EXTRN	__security_check_cookie:PROC
EXTRN	__security_cookie:QWORD
EXTRN	_fltused:DWORD
;	COMDAT ?_OptionsStorage@?1??__local_stdio_printf_options@@9@4_KA
_BSS	SEGMENT
?_OptionsStorage@?1??__local_stdio_printf_options@@9@4_KA DQ 01H DUP (?) ; `__local_stdio_printf_options'::`2'::_OptionsStorage
_BSS	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$_vfprintf_l DD imagerel $LN4
	DD	imagerel $LN4+80
	DD	imagerel $unwind$_vfprintf_l
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$printf DD imagerel $LN6
	DD	imagerel $LN6+83
	DD	imagerel $unwind$printf
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?signbit@@YA_NN@Z DD imagerel $LN4
	DD	imagerel $LN4+19
	DD	imagerel $unwind$?signbit@@YA_NN@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?sz@@YAPEBDN@Z DD imagerel ?sz@@YAPEBDN@Z
	DD	imagerel ?sz@@YAPEBDN@Z+37
	DD	imagerel $unwind$?sz@@YAPEBDN@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$main DD	imagerel $LN47
	DD	imagerel $LN47+528
	DD	imagerel $unwind$main
pdata	ENDS
;	COMDAT __ymm@8000000080000000800000008000000080000000800000008000000080000000
CONST	SEGMENT
__ymm@8000000080000000800000008000000080000000800000008000000080000000 DB 00H
	DB	00H, 00H, 080H, 00H, 00H, 00H, 080H, 00H, 00H, 00H, 080H, 00H, 00H
	DB	00H, 080H, 00H, 00H, 00H, 080H, 00H, 00H, 00H, 080H, 00H, 00H, 00H
	DB	080H, 00H, 00H, 00H, 080H
CONST	ENDS
;	COMDAT __xmm@80000000800000008000000080000000
CONST	SEGMENT
__xmm@80000000800000008000000080000000 DB 00H, 00H, 00H, 080H, 00H, 00H, 00H
	DB	080H, 00H, 00H, 00H, 080H, 00H, 00H, 00H, 080H
CONST	ENDS
;	COMDAT __xmm@80000000000000008000000000000000
CONST	SEGMENT
__xmm@80000000000000008000000000000000 DB 00H, 00H, 00H, 00H, 00H, 00H, 00H
	DB	080H, 00H, 00H, 00H, 00H, 00H, 00H, 00H, 080H
CONST	ENDS
;	COMDAT __real@8000000000000000
CONST	SEGMENT
__real@8000000000000000 DQ 08000000000000000r	; -0
CONST	ENDS
;	COMDAT __real@80000000
CONST	SEGMENT
__real@80000000 DD 080000000r			; -0
CONST	ENDS
;	COMDAT ??_C@_0CM@JPKPIEDH@_mm256_sub_ps?$CIx?0?5set1?$CI?90?40f?$CJ?$CJ?5?5@
CONST	SEGMENT
??_C@_0CM@JPKPIEDH@_mm256_sub_ps?$CIx?0?5set1?$CI?90?40f?$CJ?$CJ?5?5@ DB '_'
	DB	'mm256_sub_ps(x, set1(-0.0f))         = %s', 0aH, 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0CM@ILNICDGM@_mm256_add_pd?$CIx?0?5_mm256_setzero@
CONST	SEGMENT
??_C@_0CM@ILNICDGM@_mm256_add_pd?$CIx?0?5_mm256_setzero@ DB '_mm256_add_p'
	DB	'd(x, _mm256_setzero_pd()) = %s', 0aH, 00H	; `string'
CONST	ENDS
;	COMDAT ??_C@_0CM@LCGOOMG@_mm256_add_ps?$CI_mm256_setzero_ps@
CONST	SEGMENT
??_C@_0CM@LCGOOMG@_mm256_add_ps?$CI_mm256_setzero_ps@ DB '_mm256_add_ps(_'
	DB	'mm256_setzero_ps(), x) = %s', 0aH, 00H	; `string'
CONST	ENDS
;	COMDAT ??_C@_0CM@KJNJIOFI@_mm256_add_ps?$CIx?0?5_mm256_setzero@
CONST	SEGMENT
??_C@_0CM@KJNJIOFI@_mm256_add_ps?$CIx?0?5_mm256_setzero@ DB '_mm256_add_p'
	DB	's(x, _mm256_setzero_ps()) = %s', 0aH, 00H	; `string'
CONST	ENDS
;	COMDAT ??_C@_0CM@OOIHBKIE@_mm_add_ps?$CIx?0?5_mm_set1_ps?$CI0?40f?$CJ@
CONST	SEGMENT
??_C@_0CM@OOIHBKIE@_mm_add_ps?$CIx?0?5_mm_set1_ps?$CI0?40f?$CJ@ DB '_mm_a'
	DB	'dd_ps(x, _mm_set1_ps(0.0f))      = %s', 0aH, 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0CM@KAFIMPEB@_mm_add_ps?$CIx?0?5_mm_setzero_ps?$CI?$CJ?$CJ@
CONST	SEGMENT
??_C@_0CM@KAFIMPEB@_mm_add_ps?$CIx?0?5_mm_setzero_ps?$CI?$CJ?$CJ@ DB '_mm'
	DB	'_add_ps(x, _mm_setzero_ps())       = %s', 0aH, 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0CJ@FMEPFAPL@scalar?5double?5?5?90?40?5?5?$CL?50?40?5?5?5?5?5@
CONST	SEGMENT
??_C@_0CJ@FMEPFAPL@scalar?5double?5?5?90?40?5?5?$CL?50?40?5?5?5?5?5@ DB 's'
	DB	'calar double  -0.0  + 0.0         = %s', 0aH, 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0CJ@MBAAFMLA@scalar?5float?5?5?5?90?40f?5?$CL?50?40f?5?5?5?5@
CONST	SEGMENT
??_C@_0CJ@MBAAFMLA@scalar?5float?5?5?5?90?40f?5?$CL?50?40f?5?5?5?5@ DB 's'
	DB	'calar float   -0.0f + 0.0f        = %s', 0aH, 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_02OLOALJBP@?$CL0@
CONST	SEGMENT
??_C@_02OLOALJBP@?$CL0@ DB '+0', 00H			; `string'
CONST	ENDS
;	COMDAT ??_C@_02OPGNMFKN@?90@
CONST	SEGMENT
??_C@_02OPGNMFKN@?90@ DB '-0', 00H			; `string'
CONST	ENDS
;	COMDAT voltbl
voltbl	SEGMENT
_volmd	DB	041H
	DB	05cH
	DB	062H
	DB	099H
voltbl	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$main DD	051f19H
	DD	01a340dH
	DD	018010dH
	DD	07006H
	DD	imagerel __GSHandlerCheck
	DD	0b0H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?sz@@YAPEBDN@Z DD 010401H
	DD	04204H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?signbit@@YA_NN@Z DD 010401H
	DD	04204H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$printf DD 041b01H
	DD	07017521bH
	DD	030156016H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$_vfprintf_l DD 081401H
	DD	0a6414H
	DD	095414H
	DD	083414H
	DD	070105214H
xdata	ENDS
; Function compile flags: /Ogtpy
; File D:\wsl\personal\dr\paper\toxic_compile\plan\reports_rewrites\msvc_addzero\add_zero.cpp
; File C:\Program Files (x86)\Windows Kits\10\include\10.0.26100.0\ucrt\corecrt_math.h
; File D:\wsl\personal\dr\paper\toxic_compile\plan\reports_rewrites\msvc_addzero\add_zero.cpp
; File C:\Program Files (x86)\Windows Kits\10\include\10.0.26100.0\ucrt\corecrt_math.h
; File D:\wsl\personal\dr\paper\toxic_compile\plan\reports_rewrites\msvc_addzero\add_zero.cpp
; File C:\Program Files (x86)\Windows Kits\10\include\10.0.26100.0\ucrt\corecrt_math.h
; File D:\wsl\personal\dr\paper\toxic_compile\plan\reports_rewrites\msvc_addzero\add_zero.cpp
; File C:\Program Files (x86)\Windows Kits\10\include\10.0.26100.0\ucrt\corecrt_math.h
; File D:\wsl\personal\dr\paper\toxic_compile\plan\reports_rewrites\msvc_addzero\add_zero.cpp
; File C:\Program Files (x86)\Windows Kits\10\include\10.0.26100.0\ucrt\corecrt_math.h
; File D:\wsl\personal\dr\paper\toxic_compile\plan\reports_rewrites\msvc_addzero\add_zero.cpp
; File C:\Program Files (x86)\Windows Kits\10\include\10.0.26100.0\ucrt\corecrt_math.h
; File D:\wsl\personal\dr\paper\toxic_compile\plan\reports_rewrites\msvc_addzero\add_zero.cpp
; File C:\Program Files (x86)\Windows Kits\10\include\10.0.26100.0\ucrt\corecrt_math.h
; File D:\wsl\personal\dr\paper\toxic_compile\plan\reports_rewrites\msvc_addzero\add_zero.cpp
; File C:\Program Files (x86)\Windows Kits\10\include\10.0.26100.0\ucrt\corecrt_math.h
; File D:\wsl\personal\dr\paper\toxic_compile\plan\reports_rewrites\msvc_addzero\add_zero.cpp
;	COMDAT main
_TEXT	SEGMENT
vf$ = 32
vd$ = 40
out$ = 48
in$ = 80
ind$ = 112
outd$ = 144
__$ArrayPad$ = 176
main	PROC						; COMDAT

; 23   : int main() {

$LN47:
	mov	QWORD PTR [rsp+8], rbx
	push	rdi
	sub	rsp, 192				; 000000c0H
	mov	rax, QWORD PTR __security_cookie
	xor	rax, rsp
	mov	QWORD PTR __$ArrayPad$[rsp], rax

; 24   :     float in[8] = {-0.0f, -0.0f, -0.0f, -0.0f, -0.0f, -0.0f, -0.0f, -0.0f}, out[8];
; 25   :     double ind[4] = {-0.0, -0.0, -0.0, -0.0}, outd[4];

	movdqa	xmm1, XMMWORD PTR __xmm@80000000000000008000000000000000
	movdqa	xmm0, XMMWORD PTR __xmm@80000000800000008000000080000000
	movups	XMMWORD PTR in$[rsp], xmm0
	movups	XMMWORD PTR in$[rsp+16], xmm0

; 26   :     volatile float vf = -0.0f; volatile double vd = -0.0;

	movss	xmm0, DWORD PTR __real@80000000
	movss	DWORD PTR vf$[rsp], xmm0
	movups	XMMWORD PTR ind$[rsp], xmm1
	movups	XMMWORD PTR ind$[rsp+16], xmm1
	movsd	xmm1, QWORD PTR __real@8000000000000000
	movsd	QWORD PTR vd$[rsp], xmm1

; 27   :     std::printf("scalar float   -0.0f + 0.0f        = %s\n", sz(scalar_f(vf)));

	movss	xmm0, DWORD PTR vf$[rsp]
	call	?scalar_f@@YAMM@Z			; scalar_f
	cvtss2sd xmm0, xmm0
; File C:\Program Files (x86)\Windows Kits\10\include\10.0.26100.0\ucrt\corecrt_math.h

; 346  :         return _dsign(_X) != 0;

	call	_dsign
; File D:\wsl\personal\dr\paper\toxic_compile\plan\reports_rewrites\msvc_addzero\add_zero.cpp

; 21   : static const char* sz(double v) { return std::signbit(v) ? "-0" : "+0"; }

	test	eax, eax
	lea	rbx, OFFSET FLAT:??_C@_02OLOALJBP@?$CL0@
	mov	rdx, rbx
	lea	rdi, OFFSET FLAT:??_C@_02OPGNMFKN@?90@
	cmovne	rdx, rdi

; 27   :     std::printf("scalar float   -0.0f + 0.0f        = %s\n", sz(scalar_f(vf)));

	lea	rcx, OFFSET FLAT:??_C@_0CJ@MBAAFMLA@scalar?5float?5?5?5?90?40f?5?$CL?50?40f?5?5?5?5@
	call	printf

; 28   :     std::printf("scalar double  -0.0  + 0.0         = %s\n", sz(scalar_d(vd)));

	movsd	xmm0, QWORD PTR vd$[rsp]
	call	?scalar_d@@YANN@Z			; scalar_d
; File C:\Program Files (x86)\Windows Kits\10\include\10.0.26100.0\ucrt\corecrt_math.h

; 346  :         return _dsign(_X) != 0;

	call	_dsign
; File D:\wsl\personal\dr\paper\toxic_compile\plan\reports_rewrites\msvc_addzero\add_zero.cpp

; 21   : static const char* sz(double v) { return std::signbit(v) ? "-0" : "+0"; }

	test	eax, eax

; 28   :     std::printf("scalar double  -0.0  + 0.0         = %s\n", sz(scalar_d(vd)));

	lea	rcx, OFFSET FLAT:??_C@_0CJ@FMEPFAPL@scalar?5double?5?5?90?40?5?5?$CL?50?40?5?5?5?5?5@

; 21   : static const char* sz(double v) { return std::signbit(v) ? "-0" : "+0"; }

	mov	rdx, rbx
	cmovne	rdx, rdi

; 28   :     std::printf("scalar double  -0.0  + 0.0         = %s\n", sz(scalar_d(vd)));

	call	printf

; 29   :     sse_ps(in, out);       std::printf("_mm_add_ps(x, _mm_setzero_ps())       = %s\n", sz(out[0]));

	lea	rdx, QWORD PTR out$[rsp]
	lea	rcx, QWORD PTR in$[rsp]
	call	?sse_ps@@YAXPEBMPEAM@Z			; sse_ps
	movss	xmm0, DWORD PTR out$[rsp]
	cvtps2pd xmm0, xmm0
; File C:\Program Files (x86)\Windows Kits\10\include\10.0.26100.0\ucrt\corecrt_math.h

; 346  :         return _dsign(_X) != 0;

	call	_dsign
; File D:\wsl\personal\dr\paper\toxic_compile\plan\reports_rewrites\msvc_addzero\add_zero.cpp

; 21   : static const char* sz(double v) { return std::signbit(v) ? "-0" : "+0"; }

	test	eax, eax

; 29   :     sse_ps(in, out);       std::printf("_mm_add_ps(x, _mm_setzero_ps())       = %s\n", sz(out[0]));

	lea	rcx, OFFSET FLAT:??_C@_0CM@KAFIMPEB@_mm_add_ps?$CIx?0?5_mm_setzero_ps?$CI?$CJ?$CJ@

; 21   : static const char* sz(double v) { return std::signbit(v) ? "-0" : "+0"; }

	mov	rdx, rbx
	cmovne	rdx, rdi

; 29   :     sse_ps(in, out);       std::printf("_mm_add_ps(x, _mm_setzero_ps())       = %s\n", sz(out[0]));

	call	printf

; 30   :     sse_ps_set1(in, out);  std::printf("_mm_add_ps(x, _mm_set1_ps(0.0f))      = %s\n", sz(out[0]));

	lea	rdx, QWORD PTR out$[rsp]
	lea	rcx, QWORD PTR in$[rsp]
	call	?sse_ps_set1@@YAXPEBMPEAM@Z		; sse_ps_set1
	movss	xmm0, DWORD PTR out$[rsp]
	cvtps2pd xmm0, xmm0
; File C:\Program Files (x86)\Windows Kits\10\include\10.0.26100.0\ucrt\corecrt_math.h

; 346  :         return _dsign(_X) != 0;

	call	_dsign
; File D:\wsl\personal\dr\paper\toxic_compile\plan\reports_rewrites\msvc_addzero\add_zero.cpp

; 21   : static const char* sz(double v) { return std::signbit(v) ? "-0" : "+0"; }

	test	eax, eax

; 30   :     sse_ps_set1(in, out);  std::printf("_mm_add_ps(x, _mm_set1_ps(0.0f))      = %s\n", sz(out[0]));

	lea	rcx, OFFSET FLAT:??_C@_0CM@OOIHBKIE@_mm_add_ps?$CIx?0?5_mm_set1_ps?$CI0?40f?$CJ@

; 21   : static const char* sz(double v) { return std::signbit(v) ? "-0" : "+0"; }

	mov	rdx, rbx
	cmovne	rdx, rdi

; 30   :     sse_ps_set1(in, out);  std::printf("_mm_add_ps(x, _mm_set1_ps(0.0f))      = %s\n", sz(out[0]));

	call	printf

; 31   :     avx_ps(in, out);       std::printf("_mm256_add_ps(x, _mm256_setzero_ps()) = %s\n", sz(out[0]));

	lea	rdx, QWORD PTR out$[rsp]
	lea	rcx, QWORD PTR in$[rsp]
	call	?avx_ps@@YAXPEBMPEAM@Z			; avx_ps
	movss	xmm0, DWORD PTR out$[rsp]
	cvtps2pd xmm0, xmm0
; File C:\Program Files (x86)\Windows Kits\10\include\10.0.26100.0\ucrt\corecrt_math.h

; 346  :         return _dsign(_X) != 0;

	call	_dsign
; File D:\wsl\personal\dr\paper\toxic_compile\plan\reports_rewrites\msvc_addzero\add_zero.cpp

; 21   : static const char* sz(double v) { return std::signbit(v) ? "-0" : "+0"; }

	test	eax, eax

; 31   :     avx_ps(in, out);       std::printf("_mm256_add_ps(x, _mm256_setzero_ps()) = %s\n", sz(out[0]));

	lea	rcx, OFFSET FLAT:??_C@_0CM@KJNJIOFI@_mm256_add_ps?$CIx?0?5_mm256_setzero@

; 21   : static const char* sz(double v) { return std::signbit(v) ? "-0" : "+0"; }

	mov	rdx, rbx
	cmovne	rdx, rdi

; 31   :     avx_ps(in, out);       std::printf("_mm256_add_ps(x, _mm256_setzero_ps()) = %s\n", sz(out[0]));

	call	printf

; 32   :     avx_ps_rev(in, out);   std::printf("_mm256_add_ps(_mm256_setzero_ps(), x) = %s\n", sz(out[0]));

	lea	rdx, QWORD PTR out$[rsp]
	lea	rcx, QWORD PTR in$[rsp]
	call	?avx_ps_rev@@YAXPEBMPEAM@Z		; avx_ps_rev
	movss	xmm0, DWORD PTR out$[rsp]
	cvtps2pd xmm0, xmm0
; File C:\Program Files (x86)\Windows Kits\10\include\10.0.26100.0\ucrt\corecrt_math.h

; 346  :         return _dsign(_X) != 0;

	call	_dsign
; File D:\wsl\personal\dr\paper\toxic_compile\plan\reports_rewrites\msvc_addzero\add_zero.cpp

; 21   : static const char* sz(double v) { return std::signbit(v) ? "-0" : "+0"; }

	test	eax, eax

; 32   :     avx_ps_rev(in, out);   std::printf("_mm256_add_ps(_mm256_setzero_ps(), x) = %s\n", sz(out[0]));

	lea	rcx, OFFSET FLAT:??_C@_0CM@LCGOOMG@_mm256_add_ps?$CI_mm256_setzero_ps@

; 21   : static const char* sz(double v) { return std::signbit(v) ? "-0" : "+0"; }

	mov	rdx, rbx
	cmovne	rdx, rdi

; 32   :     avx_ps_rev(in, out);   std::printf("_mm256_add_ps(_mm256_setzero_ps(), x) = %s\n", sz(out[0]));

	call	printf

; 33   :     avx_pd(ind, outd);     std::printf("_mm256_add_pd(x, _mm256_setzero_pd()) = %s\n", sz(outd[0]));

	lea	rdx, QWORD PTR outd$[rsp]
	lea	rcx, QWORD PTR ind$[rsp]
	call	?avx_pd@@YAXPEBNPEAN@Z			; avx_pd
; File C:\Program Files (x86)\Windows Kits\10\include\10.0.26100.0\ucrt\corecrt_math.h

; 346  :         return _dsign(_X) != 0;

	movsd	xmm0, QWORD PTR outd$[rsp]
	call	_dsign
; File D:\wsl\personal\dr\paper\toxic_compile\plan\reports_rewrites\msvc_addzero\add_zero.cpp

; 21   : static const char* sz(double v) { return std::signbit(v) ? "-0" : "+0"; }

	test	eax, eax
	mov	rdx, rbx
	cmovne	rdx, rdi

; 33   :     avx_pd(ind, outd);     std::printf("_mm256_add_pd(x, _mm256_setzero_pd()) = %s\n", sz(outd[0]));

	lea	rcx, OFFSET FLAT:??_C@_0CM@ILNICDGM@_mm256_add_pd?$CIx?0?5_mm256_setzero@
	call	printf

; 34   :     avx_ps_sub(in, out);   std::printf("_mm256_sub_ps(x, set1(-0.0f))         = %s\n", sz(out[0]));

	lea	rdx, QWORD PTR out$[rsp]
	lea	rcx, QWORD PTR in$[rsp]
	call	?avx_ps_sub@@YAXPEBMPEAM@Z		; avx_ps_sub
	movss	xmm0, DWORD PTR out$[rsp]
	cvtps2pd xmm0, xmm0
; File C:\Program Files (x86)\Windows Kits\10\include\10.0.26100.0\ucrt\corecrt_math.h

; 346  :         return _dsign(_X) != 0;

	call	_dsign
; File D:\wsl\personal\dr\paper\toxic_compile\plan\reports_rewrites\msvc_addzero\add_zero.cpp

; 21   : static const char* sz(double v) { return std::signbit(v) ? "-0" : "+0"; }

	test	eax, eax

; 34   :     avx_ps_sub(in, out);   std::printf("_mm256_sub_ps(x, set1(-0.0f))         = %s\n", sz(out[0]));

	lea	rcx, OFFSET FLAT:??_C@_0CM@JPKPIEDH@_mm256_sub_ps?$CIx?0?5set1?$CI?90?40f?$CJ?$CJ?5?5@

; 21   : static const char* sz(double v) { return std::signbit(v) ? "-0" : "+0"; }

	cmovne	rbx, rdi

; 34   :     avx_ps_sub(in, out);   std::printf("_mm256_sub_ps(x, set1(-0.0f))         = %s\n", sz(out[0]));

	mov	rdx, rbx
	call	printf

; 35   :     return 0;

	xor	eax, eax

; 36   : }

	mov	rcx, QWORD PTR __$ArrayPad$[rsp]
	xor	rcx, rsp
	call	__security_check_cookie
	mov	rbx, QWORD PTR [rsp+208]
	add	rsp, 192				; 000000c0H
	pop	rdi
	ret	0
main	ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File D:\wsl\personal\dr\paper\toxic_compile\plan\reports_rewrites\msvc_addzero\add_zero.cpp
; File C:\Program Files (x86)\Windows Kits\10\include\10.0.26100.0\ucrt\corecrt_math.h
; File D:\wsl\personal\dr\paper\toxic_compile\plan\reports_rewrites\msvc_addzero\add_zero.cpp
;	COMDAT ?sz@@YAPEBDN@Z
_TEXT	SEGMENT
v$ = 48
?sz@@YAPEBDN@Z PROC					; sz, COMDAT

; 21   : static const char* sz(double v) { return std::signbit(v) ? "-0" : "+0"; }

	sub	rsp, 40					; 00000028H
; File C:\Program Files (x86)\Windows Kits\10\include\10.0.26100.0\ucrt\corecrt_math.h

; 346  :         return _dsign(_X) != 0;

	call	_dsign
; File D:\wsl\personal\dr\paper\toxic_compile\plan\reports_rewrites\msvc_addzero\add_zero.cpp

; 21   : static const char* sz(double v) { return std::signbit(v) ? "-0" : "+0"; }

	test	eax, eax
	lea	rdx, OFFSET FLAT:??_C@_02OPGNMFKN@?90@
	lea	rcx, OFFSET FLAT:??_C@_02OLOALJBP@?$CL0@
	cmovne	rcx, rdx
	mov	rax, rcx
	add	rsp, 40					; 00000028H
	ret	0
?sz@@YAPEBDN@Z ENDP					; sz
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File D:\wsl\personal\dr\paper\toxic_compile\plan\reports_rewrites\msvc_addzero\add_zero.cpp
;	COMDAT ?avx_ps_sub@@YAXPEBMPEAM@Z
_TEXT	SEGMENT
in$ = 8
out$ = 16
?avx_ps_sub@@YAXPEBMPEAM@Z PROC				; avx_ps_sub, COMDAT

; 19   : NOINLINE void avx_ps_sub(const float* in, float* out)  { _mm256_storeu_ps(out, _mm256_sub_ps(_mm256_loadu_ps(in), _mm256_set1_ps(-0.0f))); }

	vmovups	ymm0, YMMWORD PTR [rcx]
	vsubps	ymm1, ymm0, YMMWORD PTR __ymm@8000000080000000800000008000000080000000800000008000000080000000
	vmovups	YMMWORD PTR [rdx], ymm1
	vzeroupper
	ret	0
?avx_ps_sub@@YAXPEBMPEAM@Z ENDP				; avx_ps_sub
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File D:\wsl\personal\dr\paper\toxic_compile\plan\reports_rewrites\msvc_addzero\add_zero.cpp
;	COMDAT ?avx_ps_rev@@YAXPEBMPEAM@Z
_TEXT	SEGMENT
in$ = 8
out$ = 16
?avx_ps_rev@@YAXPEBMPEAM@Z PROC				; avx_ps_rev, COMDAT

; 18   : NOINLINE void avx_ps_rev(const float* in, float* out)  { _mm256_storeu_ps(out, _mm256_add_ps(_mm256_setzero_ps(), _mm256_loadu_ps(in))); }

	vmovups	ymm1, YMMWORD PTR [rcx]
	vmovups	YMMWORD PTR [rdx], ymm1
	vzeroupper
	ret	0
?avx_ps_rev@@YAXPEBMPEAM@Z ENDP				; avx_ps_rev
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File D:\wsl\personal\dr\paper\toxic_compile\plan\reports_rewrites\msvc_addzero\add_zero.cpp
;	COMDAT ?avx_pd@@YAXPEBNPEAN@Z
_TEXT	SEGMENT
in$ = 8
out$ = 16
?avx_pd@@YAXPEBNPEAN@Z PROC				; avx_pd, COMDAT

; 17   : NOINLINE void avx_pd(const double* in, double* out) { _mm256_storeu_pd(out, _mm256_add_pd(_mm256_loadu_pd(in), _mm256_setzero_pd())); }

	vmovupd	ymm0, YMMWORD PTR [rcx]
	vmovupd	YMMWORD PTR [rdx], ymm0
	vzeroupper
	ret	0
?avx_pd@@YAXPEBNPEAN@Z ENDP				; avx_pd
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File D:\wsl\personal\dr\paper\toxic_compile\plan\reports_rewrites\msvc_addzero\add_zero.cpp
;	COMDAT ?avx_ps@@YAXPEBMPEAM@Z
_TEXT	SEGMENT
in$ = 8
out$ = 16
?avx_ps@@YAXPEBMPEAM@Z PROC				; avx_ps, COMDAT

; 16   : NOINLINE void avx_ps(const float* in, float* out)  { _mm256_storeu_ps(out, _mm256_add_ps(_mm256_loadu_ps(in), _mm256_setzero_ps())); }

	vmovups	ymm1, YMMWORD PTR [rcx]
	vmovups	YMMWORD PTR [rdx], ymm1
	vzeroupper
	ret	0
?avx_ps@@YAXPEBMPEAM@Z ENDP				; avx_ps
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File D:\wsl\personal\dr\paper\toxic_compile\plan\reports_rewrites\msvc_addzero\add_zero.cpp
;	COMDAT ?sse_ps_set1@@YAXPEBMPEAM@Z
_TEXT	SEGMENT
in$ = 8
out$ = 16
?sse_ps_set1@@YAXPEBMPEAM@Z PROC			; sse_ps_set1, COMDAT

; 15   : NOINLINE void sse_ps_set1(const float* in, float* out)  { _mm_storeu_ps(out, _mm_add_ps(_mm_loadu_ps(in), _mm_set1_ps(0.0f))); }

	movups	xmm0, XMMWORD PTR [rcx]
	movups	XMMWORD PTR [rdx], xmm0
	ret	0
?sse_ps_set1@@YAXPEBMPEAM@Z ENDP			; sse_ps_set1
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File D:\wsl\personal\dr\paper\toxic_compile\plan\reports_rewrites\msvc_addzero\add_zero.cpp
;	COMDAT ?sse_ps@@YAXPEBMPEAM@Z
_TEXT	SEGMENT
in$ = 8
out$ = 16
?sse_ps@@YAXPEBMPEAM@Z PROC				; sse_ps, COMDAT

; 14   : NOINLINE void sse_ps(const float* in, float* out)  { _mm_storeu_ps(out, _mm_add_ps(_mm_loadu_ps(in), _mm_setzero_ps())); }

	movups	xmm1, XMMWORD PTR [rcx]
	movups	XMMWORD PTR [rdx], xmm1
	ret	0
?sse_ps@@YAXPEBMPEAM@Z ENDP				; sse_ps
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File D:\wsl\personal\dr\paper\toxic_compile\plan\reports_rewrites\msvc_addzero\add_zero.cpp
;	COMDAT ?scalar_d@@YANN@Z
_TEXT	SEGMENT
x$ = 8
?scalar_d@@YANN@Z PROC					; scalar_d, COMDAT

; 13   : NOINLINE double scalar_d(double x)  { return x + 0.0; }

	xorps	xmm1, xmm1
	addsd	xmm0, xmm1
	ret	0
?scalar_d@@YANN@Z ENDP					; scalar_d
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File D:\wsl\personal\dr\paper\toxic_compile\plan\reports_rewrites\msvc_addzero\add_zero.cpp
;	COMDAT ?scalar_f@@YAMM@Z
_TEXT	SEGMENT
x$ = 8
?scalar_f@@YAMM@Z PROC					; scalar_f, COMDAT

; 12   : NOINLINE float  scalar_f(float x)   { return x + 0.0f; }

	xorps	xmm1, xmm1
	addss	xmm0, xmm1
	ret	0
?scalar_f@@YAMM@Z ENDP					; scalar_f
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File C:\Program Files (x86)\Windows Kits\10\include\10.0.26100.0\ucrt\corecrt_math.h
;	COMDAT ?signbit@@YA_NN@Z
_TEXT	SEGMENT
_X$ = 48
?signbit@@YA_NN@Z PROC					; signbit, COMDAT

; 345  :     {

$LN4:
	sub	rsp, 40					; 00000028H

; 346  :         return _dsign(_X) != 0;

	call	_dsign
	test	eax, eax
	setne	al

; 347  :     }

	add	rsp, 40					; 00000028H
	ret	0
?signbit@@YA_NN@Z ENDP					; signbit
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File C:\Program Files (x86)\Windows Kits\10\include\10.0.26100.0\ucrt\stdio.h
;	COMDAT printf
_TEXT	SEGMENT
_Format$ = 80
printf	PROC						; COMDAT

; 956  :     {

$LN6:
	mov	QWORD PTR [rsp+8], rcx
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+24], r8
	mov	QWORD PTR [rsp+32], r9
	push	rbx
	push	rsi
	push	rdi
	sub	rsp, 48					; 00000030H
	mov	rdi, rcx

; 957  :         int _Result;
; 958  :         va_list _ArgList;
; 959  :         __crt_va_start(_ArgList, _Format);

	lea	rsi, QWORD PTR _Format$[rsp+8]

; 960  :         _Result = _vfprintf_l(stdout, _Format, NULL, _ArgList);

	mov	ecx, 1
	call	__acrt_iob_func
	mov	rbx, rax

; 645  :         return __stdio_common_vfprintf(_CRT_INTERNAL_LOCAL_PRINTF_OPTIONS, _Stream, _Format, _Locale, _ArgList);

	call	__local_stdio_printf_options
	xor	r9d, r9d
	mov	QWORD PTR [rsp+32], rsi
	mov	r8, rdi
	mov	rdx, rbx
	mov	rcx, QWORD PTR [rax]
	call	__stdio_common_vfprintf

; 961  :         __crt_va_end(_ArgList);
; 962  :         return _Result;
; 963  :     }

	add	rsp, 48					; 00000030H
	pop	rdi
	pop	rsi
	pop	rbx
	ret	0
printf	ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File C:\Program Files (x86)\Windows Kits\10\include\10.0.26100.0\ucrt\stdio.h
;	COMDAT _vfprintf_l
_TEXT	SEGMENT
_Stream$ = 64
_Format$ = 72
_Locale$ = 80
_ArgList$ = 88
_vfprintf_l PROC					; COMDAT

; 644  :     {

$LN4:
	mov	QWORD PTR [rsp+8], rbx
	mov	QWORD PTR [rsp+16], rbp
	mov	QWORD PTR [rsp+24], rsi
	push	rdi
	sub	rsp, 48					; 00000030H
	mov	rbx, r9
	mov	rdi, r8
	mov	rsi, rdx
	mov	rbp, rcx

; 645  :         return __stdio_common_vfprintf(_CRT_INTERNAL_LOCAL_PRINTF_OPTIONS, _Stream, _Format, _Locale, _ArgList);

	call	__local_stdio_printf_options
	mov	r9, rdi
	mov	QWORD PTR [rsp+32], rbx
	mov	r8, rsi
	mov	rdx, rbp
	mov	rcx, QWORD PTR [rax]
	call	__stdio_common_vfprintf

; 646  :     }

	mov	rbx, QWORD PTR [rsp+64]
	mov	rbp, QWORD PTR [rsp+72]
	mov	rsi, QWORD PTR [rsp+80]
	add	rsp, 48					; 00000030H
	pop	rdi
	ret	0
_vfprintf_l ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File C:\Program Files (x86)\Windows Kits\10\include\10.0.26100.0\ucrt\corecrt_stdio_config.h
;	COMDAT __local_stdio_printf_options
_TEXT	SEGMENT
__local_stdio_printf_options PROC			; COMDAT

; 91   :         static unsigned __int64 _OptionsStorage;
; 92   :         return &_OptionsStorage;

	lea	rax, OFFSET FLAT:?_OptionsStorage@?1??__local_stdio_printf_options@@9@4_KA ; `__local_stdio_printf_options'::`2'::_OptionsStorage

; 93   :     }

	ret	0
__local_stdio_printf_options ENDP
_TEXT	ENDS
END
